//
// Generated file, do not edit! Created by opp_msgtool 6.4 from BlockChunk.msg.
//

#ifndef __INET_BLOCKCHUNK_M_H
#define __INET_BLOCKCHUNK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0604
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class BlockChunk;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>BlockChunk.msg:7</tt> by opp_msgtool.
 * <pre>
 * class BlockChunk extends FieldsChunk
 * {
 *     int blockId = 0;
 * 
 *     int previousBlockHash = 0;
 * 
 *     int blockHash = 0;
 * }
 * </pre>
 */
class BlockChunk : public ::inet::FieldsChunk
{
  protected:
    int blockId = 0;
    int previousBlockHash = 0;
    int blockHash = 0;

  private:
    void copy(const BlockChunk& other);

  protected:
    bool operator==(const BlockChunk&) = delete;

  public:
    BlockChunk();
    BlockChunk(const BlockChunk& other);
    virtual ~BlockChunk();
    BlockChunk& operator=(const BlockChunk& other);
    virtual BlockChunk *dup() const override {return new BlockChunk(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getBlockId() const;
    virtual void setBlockId(int blockId);

    virtual int getPreviousBlockHash() const;
    virtual void setPreviousBlockHash(int previousBlockHash);

    virtual int getBlockHash() const;
    virtual void setBlockHash(int blockHash);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BlockChunk& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BlockChunk& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::BlockChunk *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::BlockChunk*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_BLOCKCHUNK_M_H

