//
// Generated file, do not edit! Created by opp_msgtool 6.4 from TransactionChunk.msg.
//

#ifndef __INET_TRANSACTIONCHUNK_M_H
#define __INET_TRANSACTIONCHUNK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0604
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class TransactionChunk;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>TransactionChunk.msg:7</tt> by opp_msgtool.
 * <pre>
 * class TransactionChunk extends FieldsChunk
 * {
 *     int txId = 0;
 *     string sender;
 *     string receiver;
 *     double amount = 0;
 * }
 * </pre>
 */
class TransactionChunk : public ::inet::FieldsChunk
{
  protected:
    int txId = 0;
    ::omnetpp::opp_string sender;
    ::omnetpp::opp_string receiver;
    double amount = 0;

  private:
    void copy(const TransactionChunk& other);

  protected:
    bool operator==(const TransactionChunk&) = delete;

  public:
    TransactionChunk();
    TransactionChunk(const TransactionChunk& other);
    virtual ~TransactionChunk();
    TransactionChunk& operator=(const TransactionChunk& other);
    virtual TransactionChunk *dup() const override {return new TransactionChunk(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTxId() const;
    virtual void setTxId(int txId);

    virtual const char * getSender() const;
    virtual void setSender(const char * sender);

    virtual const char * getReceiver() const;
    virtual void setReceiver(const char * receiver);

    virtual double getAmount() const;
    virtual void setAmount(double amount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TransactionChunk& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TransactionChunk& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::TransactionChunk *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::TransactionChunk*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_TRANSACTIONCHUNK_M_H

